dist: trusty
language: java
jdk: oraclejdk8
node_js: 8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - gradle/wrapper/
env:
  - GEN_LIBRARY=typescript-node
  - GEN_LIBRARY=java
install: npm install @openapitools/openapi-generator-cli@cli-4.1.0 -g
script:  bash generate.sh $GEN_LIBRARY build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash generate.sh $GEN_LIBRARY publish
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash generate.sh $GEN_LIBRARY release
    on:
      branch: release
  - provider: script
    skip_cleanup: true
    script: bash post-release.sh
    on:
      branch: release
      condition: "$GEN_LIBRARY = java"
before_install:
  - |
    if [ -z "${signingKeyId}" ]; then
      echo "No signing the artifacts"
    else
      echo "Signing artifacts"
      openssl aes-256-cbc -K $encrypted_bb47ec883ff6_key -iv $encrypted_bb47ec883ff6_iv -in symbol-sdk-java.gpg.enc -out symbol-sdk-java.gpg -d
    fi
